import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Shield } from 'lucide-react';
import LegalFooter from '@/components/legal/LegalFooter';

const EFFECTIVE_DATE = 'March 1, 2026';
const VERSION = '1.0';

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-[#0C0C0C]">
      {/* Top nav */}
      <nav className="border-b border-neutral-800 px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <Link to="/" className="text-white font-semibold text-base tracking-tight">Proofly</Link>
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm text-neutral-400 hover:text-white transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-neutral-400 rounded"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 py-16 px-6">
        <div className="max-w-[900px] mx-auto">
          {/* Header */}
          <div className="flex items-center gap-3 mb-3">
            <Shield className="w-5 h-5 text-[#D6B98C]" />
            <span className="text-xs text-neutral-500 uppercase tracking-wider font-medium">
              Version {VERSION} · Effective {EFFECTIVE_DATE}
            </span>
          </div>
          <h1 className="text-4xl font-light text-white mb-3">Terms of Service</h1>
          <p className="text-neutral-400 text-base leading-relaxed mb-12 max-w-2xl">
            Please read these terms carefully before using Proofly. By creating an account you agree to be bound by these terms.
          </p>

          <div className="space-y-10 text-neutral-300">

            <Section title="1. Acceptance of Terms">
              <P>By creating an account or using the Proofly platform ("Service"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree, you may not access or use the Service.</P>
              <P>You must be at least 13 years of age to use this Service. By accepting these Terms, you represent that you meet this age requirement.</P>
            </Section>

            <Section title="2. Account Eligibility & Registration">
              <P>To use Proofly, you must: (a) be at least 13 years old; (b) provide accurate registration information; (c) maintain the security of your account credentials; and (d) promptly notify us of any unauthorized use.</P>
              <P>You are responsible for all activity that occurs under your account. Proofly reserves the right to suspend or terminate accounts that violate these Terms.</P>
            </Section>

            <Section title="3. Acceptable Use">
              <P>You agree NOT to:</P>
              <ul className="list-disc pl-6 space-y-1.5 text-neutral-400 text-sm leading-relaxed">
                <li>Upload or transmit malicious code, viruses, or harmful content</li>
                <li>Attempt to gain unauthorized access to the platform or other users' accounts</li>
                <li>Scrape, crawl, or systematically download platform content without written permission</li>
                <li>Abuse, harass, or threaten other users or Proofly staff</li>
                <li>Use the Service to send unsolicited communications (spam)</li>
                <li>Violate any applicable laws, including intellectual property laws</li>
                <li>Impersonate any person or entity</li>
                <li>Interfere with the security or integrity of the Service</li>
              </ul>
              <P>Violations may result in immediate account suspension or termination without notice.</P>
            </Section>

            <Section title="4. Intellectual Property">
              <P>All content, features, and functionality of the Proofly platform — including but not limited to text, graphics, logos, software, and AI-generated content provided by Proofly — are owned by Proofly or its licensors and are protected by applicable intellectual property laws.</P>
              <P>You retain ownership of content you submit ("User Content"). By submitting User Content, you grant Proofly a limited, non-exclusive license to use it solely to operate and improve the Service.</P>
              <P>AI-generated study materials, questions, and feedback generated by the platform are provided for personal educational use only and may not be redistributed, sold, or published without written permission.</P>
            </Section>

            <Section title="5. Subscription & Billing">
              <P>Certain features require a paid subscription. Subscription fees are billed in advance on a recurring basis. All payments are processed by our third-party payment processor (Stripe). We do not store your payment card information.</P>
              <P>Refunds are handled on a case-by-case basis. Proofly reserves the right to modify pricing with reasonable notice to subscribers. Subscriptions auto-renew unless cancelled before the renewal date.</P>
            </Section>

            <Section title="6. Privacy & Data">
              <P>Your use of the Service is also governed by our <a href="/privacy" className="text-[#D6B98C] hover:underline">Privacy Policy</a>, which is incorporated into these Terms by reference.</P>
            </Section>

            <Section title="7. Limitation of Liability">
              <P>TO THE MAXIMUM EXTENT PERMITTED BY LAW, PROOFLY AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</P>
              <P>Proofly is not liable for: (a) user-generated content; (b) unauthorized access to your account due to your failure to secure credentials; (c) inaccuracies in AI-generated study content; or (d) third-party service interruptions.</P>
              <P>Our total liability to you shall not exceed the amount you paid Proofly in the 12 months preceding the claim.</P>
            </Section>

            <Section title="8. Disclaimer of Warranties">
              <P>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. PROOFLY DOES NOT WARRANT THAT THE SERVICE WILL BE ERROR-FREE, UNINTERRUPTED, OR FREE OF HARMFUL COMPONENTS. AI-GENERATED CONTENT IS PROVIDED FOR EDUCATIONAL PRACTICE ONLY AND DOES NOT CONSTITUTE OFFICIAL COLLEGE BOARD OR AP EXAM MATERIALS.</P>
            </Section>

            <Section title="9. Account Termination">
              <P>You may delete your account at any time through your account settings. Upon deletion, your personal data will be removed in accordance with our Privacy Policy, except where retention is required by law.</P>
              <P>Proofly may suspend or terminate your account at any time for violation of these Terms, with or without notice.</P>
            </Section>

            <Section title="10. Policy Updates">
              <P>We may update these Terms from time to time. When we make material changes, we will notify you via email or in-app notification and require re-acceptance before continued use of the Service. The version and effective date are shown at the top of this page.</P>
            </Section>

            <Section title="11. Governing Law & Dispute Resolution">
              <P>These Terms are governed by the laws of the State of Arizona, United States, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules, except that either party may seek injunctive relief in a court of competent jurisdiction.</P>
            </Section>

            <Section title="12. Contact">
              <P>For questions about these Terms, contact us at <a href="mailto:legal@proofly.com" className="text-[#D6B98C] hover:underline">legal@proofly.com</a>.</P>
            </Section>

          </div>

          {/* Bottom links */}
          <div className="mt-16 pt-8 border-t border-neutral-800 flex flex-wrap gap-6 text-sm text-neutral-500">
            <a href="/privacy" className="hover:text-neutral-300 transition-colors">Privacy Policy</a>
            <Link to="/" className="hover:text-neutral-300 transition-colors">Home</Link>
          </div>
        </div>
      </main>

      <LegalFooter />
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="text-xl font-semibold text-white mb-4 pb-2 border-b border-neutral-800">{title}</h2>
      <div className="space-y-3">{children}</div>
    </div>
  );
}

function P({ children, className = '' }) {
  return <p className={`text-neutral-400 text-sm leading-relaxed ${className}`}>{children}</p>;
}