import { base44 } from '@/api/base44Client';

/**
 * Export utilities for LaTeX and PDF generation
 * Nonprofit-licensed, educator-friendly
 */

export const generateLatexDocument = (content, title = 'Proofly Document') => {
  const header = `\\documentclass[12pt]{article}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{geometry}
\\geometry{margin=1in}

\\title{${title}}
\\author{Generated by Proofly (Nonprofit Educational Platform)}
\\date{\\today}

\\begin{document}
\\maketitle

`;

  const footer = `
\\end{document}`;

  return header + content + footer;
};

export const examToLatex = (exam, questions, answers = {}, includeAnswers = false) => {
  let latex = `\\section*{${exam.subject_name || 'Exam'}}
\\textit{Time Limit: ${exam.time_limit_minutes} minutes}
\\textit{Total Questions: ${exam.total_questions}}

\\vspace{1em}

`;

  questions.forEach((q, idx) => {
    latex += `\\subsection*{Question ${idx + 1}}
${q.question_text}

\\begin{enumerate}
\\item[(A)] ${q.choice_a}
\\item[(B)] ${q.choice_b}
\\item[(C)] ${q.choice_c}
\\item[(D)] ${q.choice_d}
\\end{enumerate}

`;

    if (includeAnswers) {
      latex += `\\textbf{Answer:} ${q.correct_answer}

\\textbf{Explanation:} ${q.explanation}

`;
    }

    if (answers[idx]) {
      latex += `\\textit{Your answer: ${answers[idx]}}

`;
    }

    latex += `\\vspace{1em}

`;
  });

  return latex;
};

export const worksheetToLatex = (title, problems, includeSolutions = false) => {
  let latex = `\\section*{${title}}

`;

  problems.forEach((problem, idx) => {
    latex += `\\subsection*{Problem ${idx + 1}}
${problem.question}

`;

    if (includeSolutions && problem.solution) {
      latex += `\\textbf{Solution:}

${problem.solution}

`;
    }

    latex += `\\vspace{2em}

`;
  });

  return latex;
};

export const downloadLatexFile = (latexContent, filename = 'document.tex') => {
  const blob = new Blob([latexContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generatePDF = async (latexContent) => {
  // Convert LaTeX to PDF using InvokeLLM with structured rendering
  const prompt = `Convert this LaTeX document to a clean, professional PDF.

LaTeX Content:
${latexContent}

Return a properly formatted academic document.`;

  try {
    // For now, we'll use a simple approach - download LaTeX and let users compile locally
    // In production, you'd integrate with a LaTeX-to-PDF service
    throw new Error('PDF generation requires LaTeX compiler. Download .tex file and compile locally with pdflatex.');
  } catch (e) {
    throw e;
  }
};

export const createLicenseFooter = () => {
  return `
\\vspace{2em}
\\hrule
\\vspace{0.5em}
\\textit{\\small This document was generated by Proofly, a nonprofit educational platform.}
\\textit{\\small Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).}
\\textit{\\small Free to use, share, and adapt with attribution.}
`;
};